dnf:
  - zsh
  - neovim
  - fastfetch
  - bat
  - ripgrep
  - eza
  - tio
  - python3
  - python3-pip

pip:
  - platformio
  - rshell
  - mpremote

binary:
  - host-spawn: https://github.com/1player/host-spawn/releases/download/v1.6.1/host-spawn-x86_64
