dnf:
  - zsh
  - neovim
  - neofetch
  - bat
  - ripgrep
  - lsd
  - tio
  - python3
  - python3-pip

pip:
  - platformio
  - rshell
  - mpremote

binary:
  - host-spawn: https://github.com/1player/host-spawn/releases/download/1.6.0/host-spawn-x86_64
